[Success Page]: Add success page to project badging
AllInOpenSource/ProjectBadging pull request #59
Opened 2023-08-02 13:18 UTC by Teek-tech

2023-08-11 10:14 UTC, misspee007 approved these changes

2023-08-11 10:15 UTC, misspee007 requested changes
@Teek-tech You have merge conflicts.

2023-08-11 10:21 UTC, Teek-tech commented
I will fix this and push.
Thanks @misspee007

2023-08-26 15:00 UTC, misspee007 approved these changes

2023-08-26 15:00 UTC, merged